apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  # revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        tier: backend
    spec:
      restartPolicy: Always
      containers:
      - name: server-app
        image: mimani/sample-server:b04e0ba3b9fbb84b9d987525c5cba70d0917682e
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 250m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 150Mi

        # https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

        envFrom:
        - configMapRef:
            name: app-env-config

        # env:
        # - name: LOG_LEVEL
        #   valueFrom:
        #     configMapKeyRef:
        #       name: app_env_config
        #       key: LOG_LEVEL

        # volumeMounts:
        # - name: envVolume
        #   mountPath: /app/.env

      # volumes:
      # - name: envVolume
      #   configMap:
      #     name: app_env_config