name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  docker:

    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: ls directory
      #   id: vars_ls
      #   run: echo "::set-output name=sha_short::$(pwd; ls)"

      # - name: Define custom tag
      #   id: Short
      #   run: echo "::set-output name=sha_short::$(cd sample-service; git rev-parse --short HEAD)"
      
      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          push: true
          tags:  mimani/sample-server:${{ github.sha }}, mimani/sample-server:latest

      # # - name: Build and push
      # #   uses: docker/build-push-action@v3
      # #   with:
      # #     push: true
      # #     tags: mimani/sample-server:${{ steps.vars.outputs.sha_short }}

      
      # Extract metadata (tags, labels) for Docker
      # - name: Extract metadata (tags, labels) for Docker
      #   uses: docker/metadata-action@v4
      #   id: meta
      #   with:
      #     images: ghcr.io/${{ github.repository }}
      #     tags: |
      #       type=semver,pattern=v{{major}}.{{minor}}.{{patch}}-dev
      #       type=semver,pattern={{major}}.{{minor}}.{{patch}}-dev
      #       type=semver,pattern=v{{major}}.{{minor}}-dev
      #       type=semver,pattern={{major}}.{{minor}}-dev
      #       type=semver,pattern=v{{major}}-dev
      #       type=semver,pattern={{major}}-dev
      #       type=raw,value=dev
      #     flavor: |
      #       latest=false

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     # context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     # platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/arm/v6,linux/s390x